---
- hosts: ise
  gather_facts: false

  vars:
    switches_csv: "switches.csv"

  tasks:
    - name: Read switches from CSV
      community.general.read_csv:
        path: "{{ switches_csv }}"
      register: switches_data
      delegate_to: localhost
      run_once: true

    - name: Show parsed CSV data
      ansible.builtin.debug:
        msg: "{{ switches_data.list }}"

    - name: Create Network Device Group
      cisco.ise.network_device_group:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        description: "Retail"
        name: "Departments#Departments#Retail"
        othername: "Departments"
      register: result_dept

    - name: Show group results
      ansible.builtin.debug:
        msg: "{{ result_dept }}"

    - name: Create Network Devices from CSV
      cisco.ise.network_device:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        NetworkDeviceGroupList:
          - "{{ item.group }}"
        NetworkDeviceIPList:
          - ipaddress: "{{ item.ip }}"
            mask: "{{ item.mask | int }}"
        authenticationSettings:
          dtlsRequired: true
          enableKeyWrap: true
          keyEncryptionKey: "{{ keyEncryptionKey }}"
          keyInputFormat: ASCII
          messageAuthenticatorCodeKey: "{{ macKey }}"
          radiusSharedSecret: "{{ radiusSharedSecret }}"
        name: "{{ item.name }}"
      loop: "{{ switches_data.list }}"
      loop_control:
        label: "{{ item.name }} ({{ item.ip }})"
      register: result_devices
