---
- hosts: ise
  gather_facts: false
    
  tasks:
    - name: Create Endpoint Identity Group
      cisco.ise.endpoint_group:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        description: PCI POS Devices
        name: Point-of-Sale
        systemDefined: false
      register: endpoint_group
  
    - name: Create Endpoint
      cisco.ise.endpoint:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        description: Credit Card Terminal
        mac: 12-AE-32-43-F1-29
        name: Credit-Card-Terminal-1
        identityStore: Point-of-Sale
        identityStoreId: "{{ endpoint_group.ise_response.id }}"
        staticGroupAssignment: true
       
    - name: Create Library Condition
      cisco.ise.network_access_conditions:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        attributeName: Name
        attributeValue: Endpoint Identity Groups:Point-of-Sale
        conditionType: LibraryConditionAttributes
        description: null
        dictionaryName: IdentityGroup
        dictionaryValue: null
        isNegate: false
        name: PCI-Devices
        operator: equals
      register: condition
  
    - name: Create Network Policy Set
      cisco.ise.network_access_policy_set:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        state: present
        condition:
          conditionType: ConditionReference
          isNegate: false
          name: Wired_MAB
          description: PCI Policy Set
          id: 8a9e89f0-4592-4148-be4a-ea4364a2b50a
          default: false
        description: PCI Devices
        isProxy: false
        rank: 00
        serviceName: Default Network Access
        name: PCI Policy Set
      register: policy_set
      
    - name: Create Network Access Authn Policy
      cisco.ise.network_access_authentication_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        identitySourceName: Internal Endpoints
        ifAuthFail: REJECT
        ifProcessFail: DROP
        ifUserNotFound: CONTINUE
        rule:
          default: true
          name: Default
          rank: 0
          state: enabled
        policyId: "{{ policy_set.ise_response.id }}"
     
    - name: Create Network Access Authz Policy
      cisco.ise.network_access_authorization_rules:
        ise_hostname: "{{ ansible_host }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "false"
        policyId: "{{ policy_set.ise_response.id }}"
        rule:
          condition:
            conditionType: ConditionReference
            isNegate: false
            name: PCI-Devices
            id: "{{ condition.ise_response.id }}"
          default: false
          name: Only Allow POS Systems
          rank: 0
          state: enabled
        securityGroup: Point_of_Sale_Systems
        profile:
        - PermitAccess

    - name: Display Results
      ansible.builtin.debug:
        msg: 
          - "New endpoint group {{ endpoint_group.ise_response.name }} created."
          - "New library condition {{ condition.ise_response.name }} created."
          - "New network policy set {{ policy_set.ise_response.name }} created."
          - "New authentication policy applied."
          - "New authorization policy applied."
